const categoriesStore = [
  {
    id: 1,
    name: "Astromélias",
    products: [
      {
        id: 1,
        name: "Mega Buquê Supremo Laranja",
        old_price: "849,00",
        price: "722,42",
        img: require("../../img/mega-buque-supremo-laranja.webp"),
      },
      {
        id: 2,
        name: "Buquê Império com Astromélias Roxas",
        old_price: "179,90",
        price: "109,90",
        img: require("../../img/buque-imperio-com-astromelias-roxas.webp"),
      },
      {
        id: 3,
        name: "Mega Buquê Supremo Vermelho",
        old_price: "839,90",
        price: "713,92",
        img: require("../../img/mega-buque-supremo-vermelho.webp"),
      },
      {
        id: 4,
        name: "Buquê de Astromélias Laranja com 10 unidades",
        old_price: "109,90",
        price: "89,90",
        img: require("../../img/buque-de-astromelias-laranja-com-10-unidades.webp"),
      },
      {
        id: 5,
        name: "Buquê Império com Astromélias Vermelhas",
        old_price: "149,90",
        price: "79,90",
        img: require("../../img/buque-imperio-com-astromelias-vermelhas.webp"),
      },
      {
        id: 6,
        name: "Buquê Império com Astromélias Brancas",
        old_price: "149,90",
        price: "79,90",
        img: require("../../img/buque-imperio-com-astromelias-brancas.webp"),
      },
      {
        id: 7,
        name: "Buquê Império com Astromélias Cor de Rosa",
        old_price: "149,90",
        price: "79,90",
        img: require("../../img/buque-imperio-com-astromelias-cor-de-rosa.webp"),
      },
      {
        id: 8,
        name: "Buquê Império com Astromélias Laranjas",
        old_price: "149,90",
        price: "79,90",
        img: require("../../img/buque-imperio-com-astromelias-laranjas.webp"),
      },
    ],
  },
  {
    id: 2,
    name: "Flores Secas",
    products: [
      {
        id: 9,
        name: "Buquê de Flores Secas e Angel",
        old_price: "239,90",
        price: "229,90",
        img: require("../../img/flores-secas-angel.webp"),
      },
      {
        id: 10,
        name: "Buquê Criativo de Flores Secas Sortidas",
        old_price: "89,90",
        price: "69,90",
        img: require("../../img/criativo-flores-secas-sortidas.webp"),
      },
      {
        id: 11,
        name: "Buquê Flores Secas Campestre Laranja",
        old_price: "149,90",
        price: "129,90",
        img: require("../../img/flores-secas-campestre-laranja.webp"),
      },
      {
        id: 12,
        name: "Buquê de Flores Secas e Stitch",
        old_price: "239,90",
        price: "229,90",
        img: require("../../img/flores-secas-stitch.webp"),
      },
      {
        id: 13,
        name: "Buquê Poesia de Flores Secas Azuis",
        old_price: "129,90",
        price: "89,90",
        img: require("../../img/flores-secas-azuis.webp"),
      },
      {
        id: 14,
        name: "Buquê Poesia de Flores Secas Amarelo",
        old_price: "129,90",
        price: "89,90",
        img: require("../../img/poeisa-de-flores-secas-amarelas.webp"),
      },
      {
        id: 15,
        name: "Mega Buquê de Flores Secas Coloridas",
        old_price: "319,90",
        price: "259,90",
        img: require("../../img/mega-secas-coloridas.webp"),
      },
      {
        id: 16,
        name: "Buquê Poesia de Flores Secas Roxas",
        old_price: "129,90",
        price: "89.90",
        img: require("../../img/flores-secas-roxas.webp"),
      },
      {
        id: 17,
        name: "Buquê Poesia de Flores Secas Azul Claro",
        old_price: "129,90",
        price: "89.90",
        img: require("../../img/flores-secas-azul-claro.webp"),
      },
      {
        id: 18,
        name: "Buquê Mix de Flores Secas",
        old_price: "179,90",
        price: "149,90",
        img: require("../../img/mix-flores-secas.webp"),
      },
      {
        id: 19,
        name: "Buquê Poesia de Flores Secas Coloridas",
        old_price: "129,90",
        price: "89.90",
        img: require("../../img/poesia-flores-secas-coloridas.webp"),
      },
      {
        id: 20,
        name: "Buquê Partitura de Flores Secas Roxo",
        old_price: "69,90",
        price: "49,90",
        img: require("../../img/partitura-secas-roxa.webp"),
      },
      {
        id: 21,
        name: "Buquê Partitura de Flores Secas Vermelho",
        old_price: "69,90",
        price: "49,90",
        img: require("../../img/partitura-secas-vermelhas.webp"),
      },
      {
        id: 22,
        name: "Buquê Partitura de Flores Secas Amarelas",
        old_price: "69,90",
        price: "49,90",
        img: require("../../img/paritura-secas-amarelas.webp"),
      },
      {
        id: 23,
        name: "Buquê Poesia de Flores Secas Vermelhas",
        old_price: "129,90",
        price: "89,90",
        img: require("../../img/poesia-flores-secas-vermelhas.webp"),
      },
      {
        id: 24,
        name: "Buquê Poesia de Flores Laranjas",
        old_price: "129,90",
        price: "89,90",
        img: require("../../img/poeisa-flores-laranjas.webp"),
      },
      {
        id: 25,
        name: "Buquê Poesia de Flores Secas Pink",
        old_price: "129,90",
        price: "89,90",
        img: require("../../img/poesia-flores-pink.webp"),
      },
      {
        id: 26,
        name: "Bag com Flores Secas Pink",
        old_price: "189,90",
        price: "159,90",
        img: require("../../img/bag-secas-pink.webp"),
      },
      {
        id: 27,
        name: "Buquê Partitura de Flores Secas Pink",
        old_price: "69,90",
        price: "49,90",
        img: require("../../img/partitura-secas-pink.webp"),
      },
      {
        id: 28,
        name: "Buquê Partitura de Flores Secas Azul",
        old_price: "69,90",
        price: "49,90",
        img: require("../../img/secas-azul.webp"),
      },
      {
        id: 29,
        name: "Buquê de Flores Secas Campestre Branco",
        old_price: "149,90",
        price: "129,90",
        img: require("../../img/secas-campestre.webp"),
      },
    ],
  },
  {
    id: "3",
    name: "Girassóis",
    products: [
      {
        id: 30,
        name: "Buquê Partitura Girassol",
        old_price: "69,90",
        price: "49,90",
        img: require("../../img/buque-partitura-girassol.webp"),
      },
      {
        id: 31,
        name: "Buquê 4 Estações Amarelo",
        old_price: "199,90",
        price: "179,90",
        img: require("../../img/buque-04-estacoes-amarelo.webp"),
      },
      {
        id: 32,
        name: "Buquê de 4 Girassóis Te Adoro",
        old_price: "138,90",
        price: "116,90",
        img: require("../../img/buque-de-4-girassois-te-adoro.webp"),
      },
      {
        id: 33,
        name: "Buquê Partitura Girassol e Amandita",
        old_price: "99,90",
        price: "70,80",
        img: require("../../img/buque-partitura-girassol-e-amandita.webp"),
      },
      {
        id: 34,
        name: "Buquê de 7 Girassóis Te Adoro",
        old_price: "189,90",
        price: "159,90",
        img: require("../../img/buque-de-7-girassois-te-adoro.webp"),
      },
      {
        id: 35,
        name: "Buquê de Girassol Noite Estrelada Van Gogh",
        old_price: "298,90",
        price: "275,90",
        img: require("../../img/buque-de-girassol-noite-estrelada-van-gogh.webp"),
      },
      {
        id: 36,
        name: "Girassol no Vaso com Rosas Amarelas",
        old_price: "359,90",
        price: "299,90",
        img: require("../../img/girassol-no-vaso-com-rosas-amarelas.webp"),
      },
      {
        id: 37,
        name: "Mega Buquês de Girassóis",
        old_price: "289,90",
        price: "259,90",
        img: require("../../img/mega-buques-de-girassois.webp"),
      },
      {
        id: 38,
        name: "Buquê Mix de Flores Te Amo",
        old_price: "229,90",
        price: "198,90",
        img: require("../../img/buque-mix-de-flores-te-amo.webp"),
      },
      {
        id: 39,
        name: "Buquê de Girassol e Rosas",
        old_price: "252,90",
        price: "238,90",
        img: require("../../img/buque-de-girassol-e-rosas.webp"),
      },
      {
        id: 40,
        name: "Mega Buquê com Girassóis e Rosas Brancas",
        old_price: "729,90",
        price: "639,90",
        img: require("../../img/mega-buque-com-girassois-e-rosas-brancas.webp"),
      },
    ],
  },
  {
    id: 4,
    name: "Gérberas",
    products: [
      {
        id: 41,
        name: "Buquê Presente Gérberas Vermelhas",
        old_price: "125,90",
        price: "87,90",
        img: require("../../img/buque-presente-gerberas-vermelhas.webp"),
      },
      {
        id: 41,
        name: "Buquê Presente Gérberas Amarelas",
        old_price: "125,90",
        price: "87,90",
        img: require("../../img/buque-presente-gerberas-amarelas.webp"),
      },
      {
        id: 42,
        name: "Buquê de Mix Love",
        old_price: "225,90",
        price: "195,30",
        img: require("../../img/buque-de-mix-love.webp"),
      },
      {
        id: 43,
        name: "Buquê de Gérberas Coloridas",
        old_price: "229,90",
        price: "169,90",
        img: require("../../img/buque-de-gerberas-coloridas.webp"),
      },
    ],
  },
  {
    id: 5,
    name: "Rosas Encantadas",
    products: [
      {
        id: 44,
        name: "Buquê de Gypsophila Encantada Amarelo",
        old_price: "195,90",
        price: "165,90",
        img: require("../../img/buque-de-gypsophila-encantada-amarelo.webp"),
      },
      {
        id: 45,
        name: "Buquê de Gypsophila Encantada Azul Claro",
        old_price: "195,90",
        price: "165,90",
        img: require("../../img/buque-de-gypsophila-encantada-azul-claro.webp"),
      },
      {
        id: 46,
        name: "Buquê de Gypsophila Encantada Laranja",
        old_price: "195,90",
        price: "165,90",
        img: require("../../img/buque-de-gypsophila-encantada-laranja.webp"),
      },
      {
        id: 47,
        name: "Buquê de Gypsophila Encantada Vermelho",
        old_price: "195,90",
        price: "165,90",
        img: require("../../img/buque-de-gypsophila-encantada-vermelho.webp"),
      },
      {
        id: 48,
        name: "Buquê de Gypsophila Encantada Roxo",
        old_price: "195,90",
        price: "165,90",
        img: require("../../img/buque-de-gypsophila-encantada-roxo.webp"),
      },
    ],
  },
];

function getProductData(id) {
  for (const category of categoriesStore) {
    const product = category.products.find((product) => product.id === id);
    if (product) {
      const price = parseFloat(product.price.replace(",", "."));
      const oldPrice = parseFloat(product.old_price.replace(",", "."));
      const name = product.name;
      return { ...product, price, old_price: oldPrice, name };
    }
  }
  console.log("Product data does not exist for ID: " + id);
  return undefined;
}

export { categoriesStore, getProductData };
